import {
  Category,
  Customer,
  Expense,
  Ingredient,
  PrinterSettings,
  Product,
  ProductRecipe,
  Sale,
  SaleItem,
  StockMovement,
  StoreSettings,
  Supplier,
  User,
} from '../types';
import { getTodayDateString } from '../utils/format';
import { PRESET_LOGOS } from '../utils/logoPresets';

export const SAMPLE_USERS: User[] = [
  {
    id: 'usr-admin',
    name: 'Hendra Setiawan (Owner)',
    pin: '1234',
    role: 'admin',
    phone: '08123456789',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'usr-manager-1',
    name: 'Budi Santoso (Manager)',
    pin: '2345',
    role: 'manager',
    phone: '08129876543',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'usr-cashier-1',
    name: 'Dewi Lestari (Kasir/Barista)',
    pin: '0000',
    role: 'cashier',
    phone: '08234567890',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const SAMPLE_TABLES: string[] = [
  'Meja 01 (Indoor AC)',
  'Meja 02 (Indoor AC)',
  'Meja 03 (Indoor AC)',
  'Meja 04 (Indoor AC)',
  'Meja 05 (Indoor AC)',
  'Meja 06 (Indoor Sofa)',
  'Bar Stool 01',
  'Bar Stool 02',
  'VIP Room',
  'Outdoor 01 (Smoking)',
  'Outdoor 02 (Smoking)',
  'Outdoor 03 (Smoking)',
];

export const SAMPLE_CATEGORIES: Category[] = [
  { id: 'cat-minuman', name: 'Minuman', icon: 'Coffee', color: '#0284c7', description: 'Kopi, teh, susu, jus, dan aneka minuman segar', createdAt: new Date().toISOString() },
  { id: 'cat-makanan', name: 'Makanan', icon: 'Utensils', color: '#ea580c', description: 'Nasi, mie, pasta, rice bowl, dan makanan utama', createdAt: new Date().toISOString() },
  { id: 'cat-snack', name: 'Snack', icon: 'Cookie', color: '#d97706', description: 'Camilan ringan, gorengan, french fries, pastry', createdAt: new Date().toISOString() },
  { id: 'cat-coffee', name: 'Espresso & Coffee', icon: 'Coffee', color: '#854d0e', description: 'Kopi susu, latte, espresso, manual brew', createdAt: new Date().toISOString() },
  { id: 'cat-noncoffee', name: 'Non-Coffee & Milk', icon: 'CupSoda', color: '#0284c7', description: 'Matcha, cokelat, red velvet, taro latte', createdAt: new Date().toISOString() },
  { id: 'cat-tea', name: 'Artisan Tea & Fresher', icon: 'GlassWater', color: '#16a34a', description: 'Earl grey, lychee tea, peach tea, lemon tea', createdAt: new Date().toISOString() },
  { id: 'cat-meals', name: 'Rice Bowl & Main Meals', icon: 'Utensils', color: '#ea580c', description: 'Nasi ayam sambal matah, spaghetti, yakiniku', createdAt: new Date().toISOString() },
  { id: 'cat-snacks', name: 'Snacks & Finger Food', icon: 'Cookie', color: '#d97706', description: 'French fries, platter, cireng, tahu cabe garam', createdAt: new Date().toISOString() },
  { id: 'cat-pastry', name: 'Pastry & Dessert', icon: 'Cake', color: '#9333ea', description: 'Croissant, cheesecake, waffle, toast', createdAt: new Date().toISOString() },
];

export const SAMPLE_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-1',
    name: 'PT Gayo & Flores Roastery Nusantara',
    phone: '081288991122',
    whatsapp: '6281288991122',
    address: 'Kawasan Pergudangan Kopi No. 9, Jakarta Selatan',
    email: 'sales@roasterynusantara.id',
    notes: 'Supplier biji kopi Arabica specialty dan House Blend 100% fresh roast',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sup-2',
    name: 'CV Dairy Prima Nusantara (Greenfields & Monin)',
    phone: '082155667788',
    whatsapp: '6282155667788',
    address: 'Jl. Industri Susu Segar No. 45, Cimanggis, Depok',
    email: 'order@dairyprima.co.id',
    notes: 'Distributor resmi susu fresh milk, sirup import, dan whip cream',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sup-3',
    name: 'PT Kemasan Kuliner & Food Supply',
    phone: '085733445566',
    whatsapp: '6285733445566',
    address: 'Sentra Daging & Packaging Modern Blok D-2, Jakarta Barat',
    email: 'info@kemasankuliner.com',
    notes: 'Supplier daging ayam fillet, beras wangi, cup, sedotan dan food pail',
    createdAt: new Date().toISOString(),
  },
];

export const SAMPLE_CUSTOMERS: Customer[] = [
  { id: 'cust-1', name: 'Andi Wijaya (Member Gold)', phone: '081388990011', address: 'Apartemen Senopati Tower 3', email: 'andi.w@gmail.com', totalTransactions: 14, totalSpent: 785000, createdAt: new Date().toISOString() },
  { id: 'cust-2', name: 'Nadia Salsabila', phone: '085677889900', address: 'Jl. Kemang Raya No. 12', email: 'nadiasalsa@yahoo.com', totalTransactions: 9, totalSpent: 420000, createdAt: new Date().toISOString() },
  { id: 'cust-3', name: 'Rian Pratama', phone: '089877665544', address: 'Gedung Bursa Efek Tower 1 Lt. 8', totalTransactions: 6, totalSpent: 310000, createdAt: new Date().toISOString() },
];

// ==========================================
// 1. DATA BAHAN BAKU MENTAH (RAW INGREDIENTS)
// ==========================================
export const SAMPLE_INGREDIENTS: Ingredient[] = [
  {
    id: 'ing-coffee-beans',
    name: 'Biji Kopi Arabica House Blend (Flores & Gayo)',
    category: 'kopi_espresso',
    purchaseUnit: 'kg',
    purchasePrice: 190000,
    purchaseUnitSize: 1000,
    recipeUnit: 'gram',
    conversionFactor: 1000,
    costPerRecipeUnit: 190,
    wastagePercent: 5, // 5% susut dial-in grinder
    effectiveCostPerRecipeUnit: 200, // Rp 200 / gram
    currentStock: 8500, // 8.5 kg
    minStock: 2000, // 2 kg
    supplierId: 'sup-1',
    notes: 'Medium Dark Roast untuk espresso based drink',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-fresh-milk',
    name: 'Susu Fresh Milk Full Cream (Greenfields)',
    category: 'dairy_susu',
    purchaseUnit: 'liter',
    purchasePrice: 22000,
    purchaseUnitSize: 1000,
    recipeUnit: 'ml',
    conversionFactor: 1000,
    costPerRecipeUnit: 22,
    wastagePercent: 2, // 2% steam milk residue
    effectiveCostPerRecipeUnit: 22.45,
    currentStock: 18000, // 18 liter
    minStock: 5000,
    supplierId: 'sup-2',
    notes: 'Susu cair segar untuk latte art microfoam',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-oat-milk',
    name: 'Susu Oat Barista Edition (Oatside)',
    category: 'dairy_susu',
    purchaseUnit: 'liter',
    purchasePrice: 38000,
    purchaseUnitSize: 1000,
    recipeUnit: 'ml',
    conversionFactor: 1000,
    costPerRecipeUnit: 38,
    wastagePercent: 1,
    effectiveCostPerRecipeUnit: 38.38,
    currentStock: 6000,
    minStock: 2000,
    supplierId: 'sup-2',
    notes: 'Alternatif susu plant-based vegan ramah laktosa',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-condensed-milk',
    name: 'Susu Kental Manis Carnation',
    category: 'dairy_susu',
    purchaseUnit: 'kaleng (370g)',
    purchasePrice: 14500,
    purchaseUnitSize: 370,
    recipeUnit: 'gram',
    conversionFactor: 370,
    costPerRecipeUnit: 39.19,
    wastagePercent: 2,
    effectiveCostPerRecipeUnit: 40,
    currentStock: 3700,
    minStock: 740,
    supplierId: 'sup-2',
    notes: 'Untuk campuran kopi susu creamy dan toast',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-gula-aren',
    name: 'Sirup Gula Aren Asli Kelapa Organik',
    category: 'sirup_pemanis',
    purchaseUnit: 'liter (jerigen)',
    purchasePrice: 42000,
    purchaseUnitSize: 1000,
    recipeUnit: 'ml',
    conversionFactor: 1000,
    costPerRecipeUnit: 42,
    wastagePercent: 1,
    effectiveCostPerRecipeUnit: 42.42,
    currentStock: 5000,
    minStock: 1500,
    supplierId: 'sup-2',
    notes: 'Kekentalan tinggi rasa gurih karamel alami',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-syrup-caramel',
    name: 'Sirup Karamel Monin Gourmet',
    category: 'sirup_pemanis',
    purchaseUnit: 'botol (700ml)',
    purchasePrice: 135000,
    purchaseUnitSize: 700,
    recipeUnit: 'ml',
    conversionFactor: 700,
    costPerRecipeUnit: 192.86,
    wastagePercent: 0,
    effectiveCostPerRecipeUnit: 192.86,
    currentStock: 1400,
    minStock: 350,
    supplierId: 'sup-2',
    notes: 'Sirup rasa karamel pekat impor Perancis',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-matcha-powder',
    name: 'Bubuk Matcha Uji Premium Pure (Jepang)',
    category: 'bubuk_powder',
    purchaseUnit: 'pack (500g)',
    purchasePrice: 165000,
    purchaseUnitSize: 500,
    recipeUnit: 'gram',
    conversionFactor: 500,
    costPerRecipeUnit: 330,
    wastagePercent: 2,
    effectiveCostPerRecipeUnit: 336.73,
    currentStock: 1500,
    minStock: 300,
    supplierId: 'sup-2',
    notes: 'Matcha warna hijau cerah tanpa gula tambahan',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-chocolate-powder',
    name: 'Bubuk Cokelat Belgia Dark 70%',
    category: 'bubuk_powder',
    purchaseUnit: 'pack (500g)',
    purchasePrice: 110000,
    purchaseUnitSize: 500,
    recipeUnit: 'gram',
    conversionFactor: 500,
    costPerRecipeUnit: 220,
    wastagePercent: 2,
    effectiveCostPerRecipeUnit: 224.49,
    currentStock: 2000,
    minStock: 400,
    supplierId: 'sup-2',
    notes: 'Rich cocoa butter flavour rasa pahit manis mewah',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-tea-earlgrey',
    name: 'Teh Hitam Earl Grey Bergamot Loose Leaf',
    category: 'lainnya',
    purchaseUnit: 'pack (250g)',
    purchasePrice: 85000,
    purchaseUnitSize: 250,
    recipeUnit: 'gram',
    conversionFactor: 250,
    costPerRecipeUnit: 340,
    wastagePercent: 0,
    effectiveCostPerRecipeUnit: 340,
    currentStock: 750,
    minStock: 200,
    supplierId: 'sup-1',
    notes: 'Aroma citrus bergamot menyegarkan',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-chicken-breast',
    name: 'Daging Ayam Fillet Dada Segar',
    category: 'protein_daging',
    purchaseUnit: 'kg',
    purchasePrice: 48000,
    purchaseUnitSize: 1000,
    recipeUnit: 'gram',
    conversionFactor: 1000,
    costPerRecipeUnit: 48,
    wastagePercent: 8, // 8% susut trimming lemak/kulit
    effectiveCostPerRecipeUnit: 52.17,
    currentStock: 6000, // 6 kg
    minStock: 2000,
    supplierId: 'sup-3',
    notes: 'Fillet dada ayam tanpa tulang tanpa kulit',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-rice-jasmine',
    name: 'Beras Jasmine Wangi Pulen Super',
    category: 'karbo_baking',
    purchaseUnit: 'karung (10kg)',
    purchasePrice: 175000,
    purchaseUnitSize: 10000,
    recipeUnit: 'gram',
    conversionFactor: 10000,
    costPerRecipeUnit: 17.5,
    wastagePercent: 2,
    effectiveCostPerRecipeUnit: 17.86,
    currentStock: 25000, // 25 kg
    minStock: 5000,
    supplierId: 'sup-3',
    notes: 'Nasi pulen harum untuk semua rice bowl',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-sambal-matah',
    name: 'Bumbu Sambal Matah Segar Racikan Dapur',
    category: 'bumbu_sauce',
    purchaseUnit: 'pack (500g)',
    purchasePrice: 32000,
    purchaseUnitSize: 500,
    recipeUnit: 'gram',
    conversionFactor: 500,
    costPerRecipeUnit: 64,
    wastagePercent: 3,
    effectiveCostPerRecipeUnit: 65.98,
    currentStock: 1500,
    minStock: 300,
    supplierId: 'sup-3',
    notes: 'Bawang merah, cabai rawit, serai, jeruk limau dan minyak kelapa',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-spaghetti',
    name: 'Pasta Spaghetti No. 10 (La Fonte)',
    category: 'karbo_baking',
    purchaseUnit: 'pack (500g)',
    purchasePrice: 22000,
    purchaseUnitSize: 500,
    recipeUnit: 'gram',
    conversionFactor: 500,
    costPerRecipeUnit: 44,
    wastagePercent: 2,
    effectiveCostPerRecipeUnit: 44.9,
    currentStock: 3500,
    minStock: 1000,
    supplierId: 'sup-3',
    notes: 'Pasta gandum semolina durum al dente',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-smoked-beef',
    name: 'Daging Sapi Smoked Beef Slice',
    category: 'protein_daging',
    purchaseUnit: 'pack (500g - 25 slice)',
    purchasePrice: 58000,
    purchaseUnitSize: 25,
    recipeUnit: 'slice',
    conversionFactor: 25,
    costPerRecipeUnit: 2320,
    wastagePercent: 0,
    effectiveCostPerRecipeUnit: 2320,
    currentStock: 100, // 100 slice
    minStock: 25,
    supplierId: 'sup-3',
    notes: 'Daging asap gurih untuk aglio olio dan roti panggang',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-french-fries',
    name: 'Kentang Beku Shoestring 7mm (Aviko)',
    category: 'karbo_baking',
    purchaseUnit: 'bag (2.5kg)',
    purchasePrice: 95000,
    purchaseUnitSize: 2500,
    recipeUnit: 'gram',
    conversionFactor: 2500,
    costPerRecipeUnit: 38,
    wastagePercent: 5, // 5% susut minyak gorengan
    effectiveCostPerRecipeUnit: 40,
    currentStock: 7500,
    minStock: 2500,
    supplierId: 'sup-3',
    notes: 'Kentang goreng renyah tahan lama',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-truffle-oil',
    name: 'Minyak Truffle Putih Italia & Bumbu Herb',
    category: 'bumbu_sauce',
    purchaseUnit: 'botol (250ml)',
    purchasePrice: 120000,
    purchaseUnitSize: 250,
    recipeUnit: 'ml',
    conversionFactor: 250,
    costPerRecipeUnit: 480,
    wastagePercent: 0,
    effectiveCostPerRecipeUnit: 480,
    currentStock: 450,
    minStock: 100,
    supplierId: 'sup-3',
    notes: 'Aroma jamur truffle mewah untuk kentang dan pasta',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-croissant-dough',
    name: 'Adonan Croissant Butter Frozen Unbaked',
    category: 'karbo_baking',
    purchaseUnit: 'box (12 pcs)',
    purchasePrice: 84000,
    purchaseUnitSize: 12,
    recipeUnit: 'pcs',
    conversionFactor: 12,
    costPerRecipeUnit: 7000,
    wastagePercent: 0,
    effectiveCostPerRecipeUnit: 7000,
    currentStock: 48,
    minStock: 12,
    supplierId: 'sup-3',
    notes: 'Adonan siap panggang dengan French Butter lumer',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-pack-cup-cold',
    name: 'Paper/PET Cup Cold 14oz + Lid + Sedotan Steril',
    category: 'packaging',
    purchaseUnit: 'pack (50 set)',
    purchasePrice: 42500,
    purchaseUnitSize: 50,
    recipeUnit: 'set',
    conversionFactor: 50,
    costPerRecipeUnit: 850,
    wastagePercent: 0,
    effectiveCostPerRecipeUnit: 850,
    currentStock: 450,
    minStock: 100,
    supplierId: 'sup-3',
    notes: 'Kemasan takeaway/dine-in minuman dingin',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-pack-cup-hot',
    name: 'Hot Paper Cup Double Wall 8oz + Lid + Sleeve',
    category: 'packaging',
    purchaseUnit: 'pack (50 set)',
    purchasePrice: 40000,
    purchaseUnitSize: 50,
    recipeUnit: 'set',
    conversionFactor: 50,
    costPerRecipeUnit: 800,
    wastagePercent: 0,
    effectiveCostPerRecipeUnit: 800,
    currentStock: 300,
    minStock: 80,
    supplierId: 'sup-3',
    notes: 'Kemasan minuman panas tahan panas tidak panas di tangan',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-pack-food-box',
    name: 'Food Pail Kraft Box Rice Bowl + Sendok Garpu Kayu',
    category: 'packaging',
    purchaseUnit: 'pack (50 set)',
    purchasePrice: 62500,
    purchaseUnitSize: 50,
    recipeUnit: 'set',
    conversionFactor: 50,
    costPerRecipeUnit: 1250,
    wastagePercent: 0,
    effectiveCostPerRecipeUnit: 1250,
    currentStock: 250,
    minStock: 60,
    supplierId: 'sup-3',
    notes: 'Kemasan makanan anti bocor minyak dan saus',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ing-ice-cubes',
    name: 'Es Batu Kristal Higienis Cube Tube',
    category: 'lainnya',
    purchaseUnit: 'karung (10kg)',
    purchasePrice: 16000,
    purchaseUnitSize: 10000,
    recipeUnit: 'gram',
    conversionFactor: 10000,
    costPerRecipeUnit: 1.6,
    wastagePercent: 10, // 10% mencair
    effectiveCostPerRecipeUnit: 1.78,
    currentStock: 30000,
    minStock: 10000,
    supplierId: 'sup-3',
    notes: 'Es batu bening food grade untuk minuman dingin',
    updatedAt: new Date().toISOString(),
  },
];

// ==========================================
// 2. DATA RESEP MENU LENGKAP (RECIPE BOM)
// ==========================================
export const SAMPLE_RECIPES: ProductRecipe[] = [
  {
    id: 'rec-kopi-susu',
    productId: 'prod-kopi-susu',
    productName: 'Es Kopi Susu Gula Aren Senja',
    items: [
      { ingredientId: 'ing-coffee-beans', ingredientName: 'Biji Kopi Arabica (Double Ristretto)', recipeUnit: 'gram', quantity: 18, unitCost: 200, subtotal: 3600 },
      { ingredientId: 'ing-fresh-milk', ingredientName: 'Susu Fresh Milk Greenfields', recipeUnit: 'ml', quantity: 120, unitCost: 22.45, subtotal: 2694 },
      { ingredientId: 'ing-gula-aren', ingredientName: 'Sirup Gula Aren Asli', recipeUnit: 'ml', quantity: 25, unitCost: 42.42, subtotal: 1060.5 },
      { ingredientId: 'ing-ice-cubes', ingredientName: 'Es Batu Kristal', recipeUnit: 'gram', quantity: 120, unitCost: 1.78, subtotal: 213.6 },
    ],
    packagingCost: 850, // Cup cold + Lid + Sedotan
    laborCost: 400, // Barista prep time
    utilityCost: 300, // Listrik mesin espresso & grinder
    otherCost: 0,
    totalIngredientCost: 7568,
    totalHpp: 9118, // Total HPP lengkap
    targetFoodCostPercent: 35,
    recommendedPrice: 26000,
    actualSellPrice: 24000,
    actualFoodCostPercent: 38.0,
    actualMarginPercent: 62.0,
    actualProfit: 14882,
    notes: 'Signature drink nomor 1 terlaris. Racikan double ristretto gurih legit.',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rec-americano',
    productId: 'prod-americano',
    productName: 'Iced Americano Classic',
    items: [
      { ingredientId: 'ing-coffee-beans', ingredientName: 'Biji Kopi Arabica (Double Espresso)', recipeUnit: 'gram', quantity: 18, unitCost: 200, subtotal: 3600 },
      { ingredientId: 'ing-ice-cubes', ingredientName: 'Es Batu Kristal', recipeUnit: 'gram', quantity: 150, unitCost: 1.78, subtotal: 267 },
    ],
    packagingCost: 850,
    laborCost: 350,
    utilityCost: 250,
    otherCost: 0,
    totalIngredientCost: 3867,
    totalHpp: 5317,
    targetFoodCostPercent: 28,
    recommendedPrice: 20000,
    actualSellPrice: 19000,
    actualFoodCostPercent: 28.0,
    actualMarginPercent: 72.0,
    actualProfit: 13683,
    notes: 'Bold & clean finish dengan notes cokelat karamel.',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rec-caramel-macchiato',
    productId: 'prod-caramel-macchiato',
    productName: 'Caramel Macchiato Creamy Iced',
    items: [
      { ingredientId: 'ing-coffee-beans', ingredientName: 'Biji Kopi Arabica (Double Espresso)', recipeUnit: 'gram', quantity: 18, unitCost: 200, subtotal: 3600 },
      { ingredientId: 'ing-fresh-milk', ingredientName: 'Susu Fresh Milk Greenfields', recipeUnit: 'ml', quantity: 130, unitCost: 22.45, subtotal: 2918.5 },
      { ingredientId: 'ing-syrup-caramel', ingredientName: 'Sirup Karamel Monin', recipeUnit: 'ml', quantity: 20, unitCost: 192.86, subtotal: 3857.2 },
      { ingredientId: 'ing-ice-cubes', ingredientName: 'Es Batu Kristal', recipeUnit: 'gram', quantity: 120, unitCost: 1.78, subtotal: 213.6 },
    ],
    packagingCost: 850,
    laborCost: 450,
    utilityCost: 300,
    otherCost: 0,
    totalIngredientCost: 10589,
    totalHpp: 12189,
    targetFoodCostPercent: 35,
    recommendedPrice: 35000,
    actualSellPrice: 32000,
    actualFoodCostPercent: 38.1,
    actualMarginPercent: 61.9,
    actualProfit: 19811,
    notes: 'Kombinasi vanila susu dan espresso dengan topping saus karamel leleh.',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rec-matcha-latte',
    productId: 'prod-matcha-latte',
    productName: 'Matcha Uji Premium Latte Iced',
    items: [
      { ingredientId: 'ing-matcha-powder', ingredientName: 'Bubuk Matcha Uji Jepang', recipeUnit: 'gram', quantity: 10, unitCost: 336.73, subtotal: 3367.3 },
      { ingredientId: 'ing-fresh-milk', ingredientName: 'Susu Fresh Milk Greenfields', recipeUnit: 'ml', quantity: 140, unitCost: 22.45, subtotal: 3143 },
      { ingredientId: 'ing-condensed-milk', ingredientName: 'Susu Kental Manis', recipeUnit: 'gram', quantity: 20, unitCost: 40, subtotal: 800 },
      { ingredientId: 'ing-ice-cubes', ingredientName: 'Es Batu Kristal', recipeUnit: 'gram', quantity: 120, unitCost: 1.78, subtotal: 213.6 },
    ],
    packagingCost: 850,
    laborCost: 400,
    utilityCost: 200,
    otherCost: 0,
    totalIngredientCost: 7524,
    totalHpp: 8974,
    targetFoodCostPercent: 32,
    recommendedPrice: 30000,
    actualSellPrice: 28000,
    actualFoodCostPercent: 32.1,
    actualMarginPercent: 67.9,
    actualProfit: 19026,
    notes: 'Rasa matcha autentik earthy dengan creamy susu segar.',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rec-dark-choco',
    productId: 'prod-dark-choco',
    productName: 'Signature Belgian Dark Chocolate',
    items: [
      { ingredientId: 'ing-chocolate-powder', ingredientName: 'Bubuk Cokelat Belgia 70%', recipeUnit: 'gram', quantity: 25, unitCost: 224.49, subtotal: 5612.25 },
      { ingredientId: 'ing-fresh-milk', ingredientName: 'Susu Fresh Milk Greenfields', recipeUnit: 'ml', quantity: 130, unitCost: 22.45, subtotal: 2918.5 },
      { ingredientId: 'ing-ice-cubes', ingredientName: 'Es Batu Kristal', recipeUnit: 'gram', quantity: 120, unitCost: 1.78, subtotal: 213.6 },
    ],
    packagingCost: 850,
    laborCost: 400,
    utilityCost: 200,
    otherCost: 0,
    totalIngredientCost: 8744,
    totalHpp: 10194,
    targetFoodCostPercent: 35,
    recommendedPrice: 30000,
    actualSellPrice: 27000,
    actualFoodCostPercent: 37.8,
    actualMarginPercent: 62.2,
    actualProfit: 16806,
    notes: 'Cokelat pekat lezat tidak terlalu manis favorit semua usia.',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rec-rice-bowl-matah',
    productId: 'prod-rice-bowl-matah',
    productName: 'Rice Bowl Ayam Sambal Matah Bali',
    items: [
      { ingredientId: 'ing-chicken-breast', ingredientName: 'Daging Ayam Fillet Dada (Crispy)', recipeUnit: 'gram', quantity: 130, unitCost: 52.17, subtotal: 6782.1 },
      { ingredientId: 'ing-rice-jasmine', ingredientName: 'Beras Jasmine Wangi Matang', recipeUnit: 'gram', quantity: 180, unitCost: 17.86, subtotal: 3214.8 },
      { ingredientId: 'ing-sambal-matah', ingredientName: 'Sambal Matah Segar Racikan', recipeUnit: 'gram', quantity: 35, unitCost: 65.98, subtotal: 2309.3 },
    ],
    packagingCost: 1250, // Food pail kraft + sendok garpu kayu
    laborCost: 800, // Cook & garnish
    utilityCost: 600, // Gas penggorengan & rice cooker
    otherCost: 0,
    totalIngredientCost: 12306,
    totalHpp: 14956,
    targetFoodCostPercent: 38,
    recommendedPrice: 39500,
    actualSellPrice: 36000,
    actualFoodCostPercent: 41.5,
    actualMarginPercent: 58.5,
    actualProfit: 21044,
    notes: 'Potongan ayam goreng renyah disiram sambal matah harum serai dan jeruk nipis.',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rec-truffle-fries',
    productId: 'prod-truffle-fries',
    productName: 'Truffle Parmesan French Fries',
    items: [
      { ingredientId: 'ing-french-fries', ingredientName: 'Kentang Beku Shoestring', recipeUnit: 'gram', quantity: 160, unitCost: 40, subtotal: 6400 },
      { ingredientId: 'ing-truffle-oil', ingredientName: 'Minyak Truffle & Keju Tabur', recipeUnit: 'ml', quantity: 8, unitCost: 480, subtotal: 3840 },
    ],
    packagingCost: 900,
    laborCost: 450,
    utilityCost: 500,
    otherCost: 0,
    totalIngredientCost: 10240,
    totalHpp: 12090,
    targetFoodCostPercent: 40,
    recommendedPrice: 30000,
    actualSellPrice: 28000,
    actualFoodCostPercent: 43.2,
    actualMarginPercent: 56.8,
    actualProfit: 15910,
    notes: 'Kentang goreng renyah wangi truffle dengan taburan parsley.',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rec-croissant',
    productId: 'prod-croissant',
    productName: 'French Butter Croissant Warm',
    items: [
      { ingredientId: 'ing-croissant-dough', ingredientName: 'Adonan Croissant Butter', recipeUnit: 'pcs', quantity: 1, unitCost: 7000, subtotal: 7000 },
    ],
    packagingCost: 650,
    laborCost: 350,
    utilityCost: 500, // Listrik oven baking
    otherCost: 0,
    totalIngredientCost: 7000,
    totalHpp: 8500,
    targetFoodCostPercent: 35,
    recommendedPrice: 25000,
    actualSellPrice: 22000,
    actualFoodCostPercent: 38.6,
    actualMarginPercent: 61.4,
    actualProfit: 13500,
    notes: 'Dipanggang hangat berlapis butter Prancis renyah di luar lembut di dalam.',
    updatedAt: new Date().toISOString(),
  },
];

// ==========================================
// 3. DATA PRODUK MENU CAFE & F&B
// ==========================================
export const CAFE_BANNER_SLIDES = [
  {
    id: 'slide-ambiance-1',
    type: 'ambiance',
    title: 'Suasana Hangat & Nyaman di Senja Kopi',
    subtitle: 'Tempat ideal untuk bersantai, meeting produktif, dan menikmati secangkir kopi istimewa.',
    tag: '☕ Suasana Cafe',
    badgeColor: 'bg-amber-500/80 text-white',
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80',
    actionText: 'Buka Kasir POS',
    actionTab: 'pos',
    actionBg: 'bg-amber-400 hover:bg-amber-300 text-slate-950 font-black',
  },
  {
    id: 'slide-product-1',
    type: 'product',
    title: 'Signature Es Kopi Susu Gula Aren',
    subtitle: 'Ristretto espresso bold berpadu susu murni lembut dan gula aren organik khas Nusantara.',
    tag: '⭐ Menu Bintang Terlaris',
    badgeColor: 'bg-emerald-500/80 text-white',
    imageUrl: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=1200&q=80',
    price: 24000,
    actionText: 'Pesan Sekarang (POS)',
    actionTab: 'pos',
    actionBg: 'bg-emerald-500 hover:bg-emerald-400 text-white font-bold',
  },
  {
    id: 'slide-ambiance-2',
    type: 'ambiance',
    title: 'Artisanal Barista & Single Origin Beans',
    subtitle: 'Setiap cangkir diracik presisi oleh barista handal menggunakan 100% biji kopi Arabica pilihan.',
    tag: '✨ Craft Coffee Experience',
    badgeColor: 'bg-teal-500/80 text-white',
    imageUrl: 'https://images.unsplash.com/photo-1507133750040-4a8f57021571?auto=format&fit=crop&w=1200&q=80',
    actionText: 'Kelola Resep & HPP',
    actionTab: 'recipes',
    actionBg: 'bg-white hover:bg-slate-100 text-slate-900 font-extrabold',
  },
  {
    id: 'slide-product-2',
    type: 'product',
    title: 'Warm French Butter Croissant & Pastry',
    subtitle: 'Dipanggang segar setiap pagi dengan lapisan butter harum keemasan yang super renyah.',
    tag: '🥐 Fresh From The Oven',
    badgeColor: 'bg-rose-500/80 text-white',
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=1200&q=80',
    price: 22000,
    actionText: 'Cek Stok Pastry',
    actionTab: 'inventory',
    actionBg: 'bg-rose-500 hover:bg-rose-400 text-white font-bold',
  },
  {
    id: 'slide-ambiance-3',
    type: 'ambiance',
    title: 'Aesthetic Corner & Outdoor Garden Vibe',
    subtitle: 'Koneksi Wi-Fi kencang, banyak stopkontak, dan tata ruang estetik untuk foto Instagramable.',
    tag: '🌿 Co-Working & Chill Spot',
    badgeColor: 'bg-indigo-500/80 text-white',
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80',
    actionText: 'Lihat Katalog Menu',
    actionTab: 'products',
    actionBg: 'bg-indigo-500 hover:bg-indigo-400 text-white font-bold',
  },
  {
    id: 'slide-product-3',
    type: 'product',
    title: 'Rice Bowl Ayam Sambal Matah & Comfort Meals',
    subtitle: 'Pilihan makan siang lengkap dengan ayam goreng krispi, telur omega, dan sambal matah harum.',
    tag: '🍛 Signature Main Course',
    badgeColor: 'bg-orange-500/80 text-white',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1200&q=80',
    price: 36000,
    actionText: 'Buka Kasir (POS)',
    actionTab: 'pos',
    actionBg: 'bg-orange-500 hover:bg-orange-400 text-white font-bold',
  },
];

export const PRESET_PRODUCT_IMAGES = [
  { name: 'Es Kopi Susu Aren', url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=600&q=80' },
  { name: 'Iced Americano', url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80' },
  { name: 'Caramel Macchiato', url: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=600&q=80' },
  { name: 'Cafe Latte Art', url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=600&q=80' },
  { name: 'Matcha Latte Iced', url: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=600&q=80' },
  { name: 'Belgian Dark Chocolate', url: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=600&q=80' },
  { name: 'Red Velvet Latte', url: 'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?auto=format&fit=crop&w=600&q=80' },
  { name: 'Earl Grey Milk Tea', url: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80' },
  { name: 'Iced Lychee Tea', url: 'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=600&q=80' },
  { name: 'Rice Bowl Sambal Matah', url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80' },
  { name: 'Spaghetti Aglio Olio', url: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80' },
  { name: 'Beef Yakiniku Rice Bowl', url: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=600&q=80' },
  { name: 'Truffle Parmesan Fries', url: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=600&q=80' },
  { name: 'Cireng Crispy Rujak', url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80' },
  { name: 'French Butter Croissant', url: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80' },
  { name: 'Burnt Cheesecake', url: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80' },
];

export const SAMPLE_PRODUCTS: Product[] = [
  // MINUMAN (COFFEE & NON-COFFEE & TEA)
  {
    id: 'prod-kopi-susu',
    sku: 'CFE-KPSU-01',
    barcode: '8992001001',
    name: 'Es Kopi Susu Gula Aren Senja',
    image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=600&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-minuman',
    unit: 'cup',
    buyPrice: 7568,
    hpp: 9118,
    sellPrice: 24000,
    wholesalePrice: 22000,
    margin: 62.0,
    stock: 95,
    minStock: 20,
    supplierId: 'sup-1',
    description: 'Signature coffee blend ristretto, susu segar, dan gula aren organik',
    isDiscountActive: true,
    discountType: 'percent',
    discountValue: 10, // Promo Diskon 10%
    enableTax: true,
    taxRate: 11,
    hasRecipe: true,
    recipeId: 'rec-kopi-susu',
    foodCostPercent: 38.0,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-americano',
    sku: 'CFE-AMER-02',
    barcode: '8992001002',
    name: 'Iced Americano Classic',
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-minuman',
    unit: 'cup',
    buyPrice: 3867,
    hpp: 5317,
    sellPrice: 19000,
    wholesalePrice: 17000,
    margin: 72.0,
    stock: 120,
    minStock: 25,
    supplierId: 'sup-1',
    description: 'Double espressoshot di atas air es kristal, segar tanpa ampas',
    isDiscountActive: false,
    discountType: 'percent',
    discountValue: 0,
    enableTax: true,
    taxRate: 11,
    hasRecipe: true,
    recipeId: 'rec-americano',
    foodCostPercent: 28.0,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-caramel-macchiato',
    sku: 'CFE-CRML-03',
    barcode: '8992001003',
    name: 'Caramel Macchiato Creamy Iced',
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=600&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-minuman',
    unit: 'cup',
    buyPrice: 10589,
    hpp: 12189,
    sellPrice: 32000,
    wholesalePrice: 29000,
    margin: 61.9,
    stock: 65,
    minStock: 15,
    supplierId: 'sup-1',
    description: 'Espresso dilapisi susu vanila dan sirup karamel Monin leleh',
    isDiscountActive: true,
    discountType: 'fixed',
    discountValue: 5000, // Promo Potongan Rp 5.000
    enableTax: true,
    taxRate: 10, // PB1 Resto 10%
    hasRecipe: true,
    recipeId: 'rec-caramel-macchiato',
    foodCostPercent: 38.1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-latte-hot',
    sku: 'CFE-LATH-04',
    barcode: '8992001004',
    name: 'Hot Cafe Latte with Latte Art',
    image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=600&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-minuman',
    unit: 'cup',
    buyPrice: 6300,
    hpp: 8100,
    sellPrice: 25000,
    wholesalePrice: 23000,
    margin: 67.6,
    stock: 80,
    minStock: 20,
    supplierId: 'sup-1',
    description: 'Espresso dengan steamed fresh milk bertekstur sutra dan motif latte art',
    isDiscountActive: false,
    discountType: 'percent',
    discountValue: 0,
    enableTax: true,
    taxRate: 11,
    hasRecipe: true,
    foodCostPercent: 32.4,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // NON-COFFEE (MINUMAN)
  {
    id: 'prod-matcha-latte',
    sku: 'NON-MTCH-05',
    barcode: '8992002001',
    name: 'Matcha Uji Premium Latte Iced',
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=600&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-minuman',
    unit: 'cup',
    buyPrice: 7524,
    hpp: 8974,
    sellPrice: 28000,
    wholesalePrice: 25000,
    margin: 67.9,
    stock: 70,
    minStock: 15,
    supplierId: 'sup-2',
    description: 'Bubuk Matcha murni Uji Kyoto dipadukan susu dingin lembut',
    isDiscountActive: false,
    discountType: 'percent',
    discountValue: 0,
    enableTax: true,
    taxRate: 11,
    hasRecipe: true,
    recipeId: 'rec-matcha-latte',
    foodCostPercent: 32.1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-dark-choco',
    sku: 'NON-CHOC-06',
    barcode: '8992002002',
    name: 'Signature Belgian Dark Chocolate',
    image: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=600&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-minuman',
    unit: 'cup',
    buyPrice: 8744,
    hpp: 10194,
    sellPrice: 27000,
    wholesalePrice: 24000,
    margin: 62.2,
    stock: 60,
    minStock: 15,
    supplierId: 'sup-2',
    description: 'Cokelat Belgia pekat 70% kaya antioksidan dan lezat',
    isDiscountActive: false,
    discountType: 'percent',
    discountValue: 0,
    enableTax: true,
    taxRate: 11,
    hasRecipe: true,
    recipeId: 'rec-dark-choco',
    foodCostPercent: 37.8,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-red-velvet',
    sku: 'NON-REDV-07',
    barcode: '8992002003',
    name: 'Red Velvet Cream Cheese Latte',
    image: 'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?auto=format&fit=crop&w=600&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-minuman',
    unit: 'cup',
    buyPrice: 7800,
    hpp: 9400,
    sellPrice: 27000,
    wholesalePrice: 24000,
    margin: 65.2,
    stock: 55,
    minStock: 15,
    supplierId: 'sup-2',
    description: 'Red velvet manis legit berpadu aroma vanila gurih',
    isDiscountActive: false,
    discountType: 'percent',
    discountValue: 0,
    enableTax: true,
    taxRate: 11,
    hasRecipe: false,
    foodCostPercent: 34.8,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // TEA (MINUMAN)
  {
    id: 'prod-earlgrey-tea',
    sku: 'TEA-EARL-08',
    barcode: '8992003001',
    name: 'Artisan Earl Grey Milk Tea',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-minuman',
    unit: 'cup',
    buyPrice: 4200,
    hpp: 5900,
    sellPrice: 22000,
    wholesalePrice: 20000,
    margin: 73.2,
    stock: 85,
    minStock: 20,
    supplierId: 'sup-1',
    description: 'Seduhan teh hitam bergamot wangi dengan susu segar',
    isDiscountActive: false,
    discountType: 'percent',
    discountValue: 0,
    enableTax: true,
    taxRate: 11,
    hasRecipe: false,
    foodCostPercent: 26.8,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-lychee-tea',
    sku: 'TEA-LYCH-09',
    barcode: '8992003002',
    name: 'Iced Sparkling Lychee Tea',
    image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=600&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-minuman',
    unit: 'cup',
    buyPrice: 5100,
    hpp: 6800,
    sellPrice: 23000,
    wholesalePrice: 21000,
    margin: 70.4,
    stock: 90,
    minStock: 20,
    supplierId: 'sup-2',
    description: 'Teh melati dingin dengan buah leci utuh manis menyegarkan',
    isDiscountActive: false,
    discountType: 'percent',
    discountValue: 0,
    enableTax: true,
    taxRate: 11,
    hasRecipe: false,
    foodCostPercent: 29.6,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // MAKANAN
  {
    id: 'prod-rice-bowl-matah',
    sku: 'MLS-MATAH-10',
    barcode: '8992004001',
    name: 'Rice Bowl Ayam Sambal Matah Bali',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-makanan',
    unit: 'porsi',
    buyPrice: 12306,
    hpp: 14956,
    sellPrice: 36000,
    wholesalePrice: 33000,
    margin: 58.5,
    stock: 45,
    minStock: 10,
    supplierId: 'sup-3',
    description: 'Ayam renyah berpadu sambal matah harum serai dan daun jeruk',
    isDiscountActive: false,
    discountType: 'percent',
    discountValue: 0,
    enableTax: true,
    taxRate: 10, // PB1 Resto 10%
    hasRecipe: true,
    recipeId: 'rec-rice-bowl-matah',
    foodCostPercent: 41.5,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-aglio-olio',
    sku: 'MLS-AGLIO-11',
    barcode: '8992004002',
    name: 'Spaghetti Aglio Olio Smoked Beef',
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-makanan',
    unit: 'porsi',
    buyPrice: 11800,
    hpp: 14500,
    sellPrice: 38000,
    wholesalePrice: 35000,
    margin: 61.8,
    stock: 40,
    minStock: 10,
    supplierId: 'sup-3',
    description: 'Pasta al dente ditumis bawang putih, cabai kering, dan smoked beef',
    isDiscountActive: false,
    discountType: 'percent',
    discountValue: 0,
    enableTax: true,
    taxRate: 10,
    hasRecipe: false,
    foodCostPercent: 38.2,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-beef-yakiniku',
    sku: 'MLS-YAKI-12',
    barcode: '8992004003',
    name: 'Rice Bowl Beef Yakiniku Onsen Egg',
    image: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=600&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-makanan',
    unit: 'porsi',
    buyPrice: 15500,
    hpp: 18500,
    sellPrice: 45000,
    wholesalePrice: 42000,
    margin: 58.9,
    stock: 35,
    minStock: 10,
    supplierId: 'sup-3',
    description: 'Irisan daging sapi shortplate empuk saus manis gurih khas Jepang',
    isDiscountActive: false,
    discountType: 'percent',
    discountValue: 0,
    enableTax: true,
    taxRate: 10,
    hasRecipe: false,
    foodCostPercent: 41.1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // SNACK
  {
    id: 'prod-truffle-fries',
    sku: 'SNK-TRUF-13',
    barcode: '8992005001',
    name: 'Truffle Parmesan French Fries',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=600&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-snack',
    unit: 'porsi',
    buyPrice: 10240,
    hpp: 12090,
    sellPrice: 28000,
    wholesalePrice: 25000,
    margin: 56.8,
    stock: 50,
    minStock: 15,
    supplierId: 'sup-3',
    description: 'Kentang goreng gurih harum minyak truffle dan taburan keju parmesan',
    isDiscountActive: false,
    discountType: 'percent',
    discountValue: 0,
    enableTax: false, // Non-Pajak / Bebas Pajak 0%
    taxRate: 0,
    hasRecipe: true,
    recipeId: 'rec-truffle-fries',
    foodCostPercent: 43.2,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-cireng-rujak',
    sku: 'SNK-CIRG-14',
    barcode: '8992005002',
    name: 'Cireng Crispy Bumbu Rujak Pedas',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-snack',
    unit: 'porsi',
    buyPrice: 5500,
    hpp: 7200,
    sellPrice: 20000,
    wholesalePrice: 18000,
    margin: 64.0,
    stock: 60,
    minStock: 15,
    supplierId: 'sup-3',
    description: 'Cireng kenyal gurih dicocol bumbu rujak asam manis pedas',
    isDiscountActive: false,
    discountType: 'percent',
    discountValue: 0,
    enableTax: true,
    taxRate: 11,
    hasRecipe: false,
    foodCostPercent: 36.0,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-croissant',
    sku: 'PST-CROI-15',
    barcode: '8992006001',
    name: 'French Butter Croissant Warm',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-snack',
    unit: 'pcs',
    buyPrice: 7000,
    hpp: 8500,
    sellPrice: 22000,
    wholesalePrice: 20000,
    margin: 61.4,
    stock: 35,
    minStock: 10,
    supplierId: 'sup-3',
    description: 'Croissant renyah berlapis butter harum siap santap hangat',
    isDiscountActive: true,
    discountType: 'fixed',
    discountValue: 3000, // Promo Potongan Rp 3.000
    enableTax: true,
    taxRate: 11,
    hasRecipe: true,
    recipeId: 'rec-croissant',
    foodCostPercent: 38.6,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-burnt-cheesecake',
    sku: 'PST-CHSE-16',
    barcode: '8992006002',
    name: 'Basque Burnt Cheesecake Slice',
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80',
    imageUrl: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-snack',
    unit: 'slice',
    buyPrice: 12000,
    hpp: 14500,
    sellPrice: 35000,
    wholesalePrice: 32000,
    margin: 58.6,
    stock: 25,
    minStock: 8,
    supplierId: 'sup-2',
    description: 'Kue keju panggang lembut creamy dengan permukaan karamel gosong gurih',
    isDiscountActive: false,
    discountType: 'percent',
    discountValue: 0,
    enableTax: true,
    taxRate: 11,
    hasRecipe: false,
    foodCostPercent: 41.4,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SAMPLE_EXPENSES: Expense[] = [
  { id: 'exp-1', date: getTodayDateString(), category: 'listrik', title: 'Listrik Mesin Espresso & AC Cafe', amount: 850000, notes: 'Token PLN 10.600 VA', createdAt: new Date().toISOString() },
  { id: 'exp-2', date: getTodayDateString(), category: 'operasional', title: 'Gas LPG & Es Batu Kristal Harian', amount: 160000, notes: '2 sak es kristal 20kg + 1 tabung gas', createdAt: new Date().toISOString() },
  { id: 'exp-3', date: getTodayDateString(), category: 'internet', title: 'Wi-Fi Fiber Biznet Dedicated 100 Mbps', amount: 475000, notes: 'Koneksi kasir dan pengunjung cafe', createdAt: new Date().toISOString() },
];

export const SAMPLE_STORE_SETTINGS: StoreSettings = {
  id: 'store-main',
  storeName: 'CHORD #Kopi_kebun.',
  logo: PRESET_LOGOS[0].dataUrl,
  slogan: 'Artisan Coffee & Live Vibes',
  ownerName: 'Hendra Setiawan',
  phone: '0812-3456-7890',
  whatsapp: '6281234567890',
  email: 'chord.kopikebun@resto.id',
  address: 'Jl. Senopati No. 42, Kebayoran Baru',
  city: 'Jakarta Selatan',
  province: 'DKI Jakarta',
  postalCode: '12190',
  receiptFooter: 'Terima kasih atas kunjungannya ke CHORD #Kopi_kebun.! Follow IG @chord.kopikebun untuk info live music & promo mingguan.',
  currencySymbol: 'Rp',
  taxRate: 10, // PB1 / Pajak Restoran 10%
  enableTax: false, // default disembunyikan kecuali diaktifkan
  enableRounding: true,
  isOnboarded: true,
  businessType: 'cafe',
  tables: SAMPLE_TABLES,
  wifiName: 'CHORD_KopiKebun_WiFi',
  wifiPassword: 'chordkopikebun',
};

export const SAMPLE_PRINTER_SETTINGS: PrinterSettings = {
  id: 'printer-main',
  paperSize: '58mm',
  copies: 1,
  margin: 0,
  fontSize: 'medium',
  showLogo: true,
  logoSize: 'medium',
  logoGrayscale: true,
  showCustomerName: true,
  showWifi: true,
  showAddress: true,
  showPhone: true,
  showEmail: false,
  showWebsite: false,
  showQrCode: true,
  showBarcode: false,
  showFooter: true,
  showThankYou: true,
  showHpp: false, // jangan dicetak di struk pelanggan
  showProfit: false,
  autoCut: false,
};

export function generateSampleSales(): {
  sales: Sale[];
  saleItems: SaleItem[];
  stockMovements: StockMovement[];
} {
  const today = getTodayDateString();
  const sales: Sale[] = [];
  const saleItems: SaleItem[] = [];
  const stockMovements: StockMovement[] = [];

  const txDefs = [
    {
      items: [
        { p: SAMPLE_PRODUCTS[0], q: 2, notes: 'Less Ice, Normal Sugar' }, // Kopi Susu Aren
        { p: SAMPLE_PRODUCTS[9], q: 1, notes: 'Sambal dipisah, jangan terlalu pedas' }, // Rice Bowl Matah
      ],
      time: '09:15:30',
      method: 'qris' as const,
      received: 84000,
      orderType: 'dine_in' as const,
      tableNumber: 'Meja 02 (Indoor AC)',
      custName: 'Andi Wijaya',
    },
    {
      items: [
        { p: SAMPLE_PRODUCTS[1], q: 1, notes: 'Normal' }, // Americano
        { p: SAMPLE_PRODUCTS[14], q: 2, notes: 'Hangatkan dulu' }, // Croissant
      ],
      time: '10:30:12',
      method: 'cash' as const,
      received: 70000,
      orderType: 'dine_in' as const,
      tableNumber: 'Bar Stool 01',
      custName: 'Nadia Salsabila',
    },
    {
      items: [
        { p: SAMPLE_PRODUCTS[4], q: 1, notes: 'Less Sweet' }, // Matcha Latte
        { p: SAMPLE_PRODUCTS[2], q: 1, notes: 'Extra Caramel' }, // Caramel Macchiato
        { p: SAMPLE_PRODUCTS[12], q: 1, notes: 'Garing' }, // Truffle Fries
      ],
      time: '12:05:00',
      method: 'qris' as const,
      received: 88000,
      orderType: 'dine_in' as const,
      tableNumber: 'Meja 04 (Indoor AC)',
      custName: 'Rian Pratama',
    },
    {
      items: [
        { p: SAMPLE_PRODUCTS[0], q: 4, notes: 'Semua bungkus take-away kantong terpisah' },
      ],
      time: '13:20:45',
      method: 'ewallet' as const,
      received: 96000,
      orderType: 'take_away' as const,
      tableNumber: undefined,
      custName: 'Kantor Bimasakti',
    },
    {
      items: [
        { p: SAMPLE_PRODUCTS[10], q: 2, notes: 'Pedas sedang' }, // Spaghetti Aglio Olio
        { p: SAMPLE_PRODUCTS[8], q: 2, notes: 'Batu es banyak' }, // Lychee Tea
      ],
      time: '14:45:00',
      method: 'debit' as const,
      received: 122000,
      orderType: 'dine_in' as const,
      tableNumber: 'VIP Room',
      custName: 'Meeting Tim Kreatif',
    },
    {
      items: [
        { p: SAMPLE_PRODUCTS[5], q: 2, notes: 'Dingin' }, // Dark Chocolate
        { p: SAMPLE_PRODUCTS[13], q: 1, notes: 'Bumbu rujak banyak' }, // Cireng
      ],
      time: '16:10:20',
      method: 'cash' as const,
      received: 80000,
      orderType: 'dine_in' as const,
      tableNumber: 'Outdoor 01 (Smoking)',
      custName: 'Bayu Saputra',
    },
    {
      items: [
        { p: SAMPLE_PRODUCTS[0], q: 3, notes: 'Gula aren 50%' },
        { p: SAMPLE_PRODUCTS[12], q: 2, notes: 'Saus sambal extra' },
      ],
      time: '17:35:10',
      method: 'qris' as const,
      received: 128000,
      orderType: 'take_away' as const,
      tableNumber: undefined,
      custName: 'Order GrabFood Kurir 02',
    },
    {
      items: [
        { p: SAMPLE_PRODUCTS[11], q: 1, notes: 'Telur onsen setengah matang' }, // Beef Yakiniku
        { p: SAMPLE_PRODUCTS[0], q: 1, notes: 'Normal' },
      ],
      time: '19:15:00',
      method: 'transfer' as const,
      received: 69000,
      orderType: 'dine_in' as const,
      tableNumber: 'Meja 06 (Indoor Sofa)',
      custName: 'Clara & Rekan',
    },
  ];

  txDefs.forEach((tx, idx) => {
    const saleId = `sale-${idx + 1}`;
    const invoiceNum = `INV-${today.replace(/-/g, '').slice(2)}-${1000 + idx + 1}`;

    let subtotal = 0;
    let totalHpp = 0;
    const currentSaleItems: SaleItem[] = [];

    tx.items.forEach((item, itemIdx) => {
      const p = item.p;
      const q = item.q;
      const itemSubtotal = p.sellPrice * q;
      const itemHppTotal = p.hpp * q;
      const itemProfit = itemSubtotal - itemHppTotal;

      subtotal += itemSubtotal;
      totalHpp += itemHppTotal;

      const sItem: SaleItem = {
        id: `si-${saleId}-${itemIdx + 1}`,
        saleId,
        productId: p.id,
        productName: p.name,
        barcode: p.barcode,
        unit: p.unit,
        quantity: q,
        unitBuyPrice: p.buyPrice,
        unitHpp: p.hpp,
        unitSellPrice: p.sellPrice,
        subtotal: itemSubtotal,
        discount: 0,
        total: itemSubtotal,
        profit: itemProfit,
        notes: item.notes,
      };

      currentSaleItems.push(sItem);
      saleItems.push(sItem);

      stockMovements.push({
        id: `sm-sale-${saleId}-${itemIdx}`,
        date: `${today}T${tx.time}`,
        productId: p.id,
        productName: p.name,
        type: 'out_sale',
        referenceId: saleId,
        referenceNumber: invoiceNum,
        quantity: -q,
        initialStock: p.stock + q,
        finalStock: p.stock,
        unitCost: p.hpp,
        notes: `Penjualan ${tx.orderType === 'dine_in' ? `Dine-in (${tx.tableNumber})` : 'Take-Away'} ${invoiceNum}`,
        createdAt: `${today}T${tx.time}`,
      });
    });

    const totalProfit = subtotal - totalHpp;
    const marginPercent = subtotal > 0 ? (totalProfit / subtotal) * 100 : 0;
    const change = Math.max(0, tx.received - subtotal);

    const saleRecord: Sale = {
      id: saleId,
      invoiceNumber: invoiceNum,
      date: today,
      time: tx.time,
      cashierId: idx % 2 === 0 ? 'usr-admin' : 'usr-cashier-1',
      cashierName: idx % 2 === 0 ? 'Hendra Setiawan (Owner)' : 'Dewi Lestari (Barista)',
      orderType: tx.orderType,
      tableNumber: tx.tableNumber,
      customerId: undefined,
      customerName: tx.custName,
      subtotal,
      discount: 0,
      tax: 0,
      serviceFee: 0,
      rounding: 0,
      total: subtotal,
      paymentMethod: tx.method,
      cashReceived: tx.received,
      changeAmount: change,
      totalHpp,
      totalProfit,
      profitMargin: Number(marginPercent.toFixed(1)),
      status: 'completed',
      createdAt: `${today}T${tx.time}`,
      items: currentSaleItems,
    };

    sales.push(saleRecord);
  });

  return { sales, saleItems, stockMovements };
}
